AWSTemplateFormatVersion: '2010-09-09'
Description: 'Database stack: PostgreSQL RDS instance, Subnet Group, Security Group, and Secrets Manager secret'

Parameters:
  DbName:
    Type: String
    Default: 'expense_db'
  DbUser:
    Type: String
    Default: 'expense_user'
  NetworkStackName:
    Type: String
    Description: 'Name of the network stack to import VPC and Subnet info from'

Resources:
  # Security Group for RDS to allow traffic from the ECS service
  DbSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Allow PostgreSQL inbound traffic from ECS service'
      VpcId:
        !ImportValue
          Fn::Sub: "${NetworkStackName}-VpcId"
      SecurityGroupIngress: [] # No ingress rules here, will be added by ecs-service stack

  # RDS Subnet Group
  DbSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'Subnet group for RDS'
      SubnetIds: !Split
        - ","
        - !ImportValue
            Fn::Sub: "${NetworkStackName}-PrivateSubnetIds"

  # RDS PostgreSQL Instance
  RDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: !Ref DbName
      Engine: 'postgres'
      EngineVersion: '15.15'
      DBInstanceClass: 'db.t3.micro'
      AllocatedStorage: '20'
      MasterUsername: !Ref DbUser
      MasterUserPassword: 'expense_pass' # Hardcoded password
      DBSubnetGroupName: !Ref DbSubnetGroup
      VPCSecurityGroups:
        - !Ref DbSecurityGroup
      PubliclyAccessible: false
      DeletionProtection: false

Outputs:
  DbEndpointAddress:
    Description: 'The endpoint address of the RDS instance'
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-DbEndpointAddress'
  DbSecurityGroupId:
    Description: 'The ID of the RDS Security Group'
    Value: !GetAtt DbSecurityGroup.GroupId
    Export:
      Name: !Sub '${AWS::StackName}-DbSecurityGroupId'
