AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Fargate stack: ECR Repo, Cluster, Task Definition, Service, ALB'

Parameters:
  NetworkStackName:
    Type: String
    Description: 'Name of the network stack to import VPC and Subnet info from'
  DatabaseStackName:
    Type: String
    Description: 'Name of the database stack to import secret ARN from'
  ImageURI:
    Type: String
    Description: 'The URI of the Docker image in ECR'
  JwtSecret:
    Type: String
    Description: 'The secret key for JWT generation'
    NoEcho: true

  S3BucketName:
    Type: String
    Description: 'A unique name for the S3 bucket to store receipts.'

Resources:
  # ECS Cluster
  EcsCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: 'expense-portal-cluster'

  # Security Groups
  AlbSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Allow HTTP traffic to ALB'
      VpcId:
        !ImportValue
          Fn::Sub: "${NetworkStackName}-VpcId"
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80

  EcsSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Allow traffic from ALB to ECS tasks'      
      VpcId:
        !ImportValue
          Fn::Sub: "${NetworkStackName}-VpcId"
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref AlbSecurityGroup
          IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080

  # Rule to allow ECS to talk to the DB
  EcsToDbSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        !ImportValue
          Fn::Sub: "${DatabaseStackName}-DbSecurityGroupId"
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref EcsSecurityGroup


  # Application Load Balancer (ALB)
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: 'expense-portal-alb'
      Scheme: 'internet-facing'
      Subnets: !Split
        - ","
        - !ImportValue
            Fn::Sub: "${NetworkStackName}-PublicSubnetIds"
      SecurityGroups:
        - !Ref AlbSecurityGroup

  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: 'expense-portal-tg'
      VpcId:
        !ImportValue
          Fn::Sub: "${NetworkStackName}-VpcId"
      Port: 8080
      Protocol: 'HTTP'
      TargetType: 'ip'
      HealthCheckProtocol: 'HTTP'      
      HealthCheckPath: '/api/actuator/health'
      HealthCheckIntervalSeconds: 60
      HealthCheckTimeoutSeconds: 30
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3

  Listener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: 'HTTP'
      DefaultActions:
        - Type: 'forward'
          TargetGroupArn: !Ref TargetGroup

  # IAM Roles for ECS Task
  TaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ['ecs-tasks.amazonaws.com']
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'


  TaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ['ecs-tasks.amazonaws.com']
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: 's3-receipts-access'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                Resource: !Sub 'arn:aws:s3:::${ReceiptsBucket}/*'

  # S3 Bucket for storing receipts
  ReceiptsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [HasS3BucketName, !Ref S3BucketName, !Sub 'expense-receipts-${AWS::AccountId}-${AWS::Region}']
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true


  # CloudWatch Log Group for the ECS Task
  TaskLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/ecs/${AWS::StackName}'
      RetentionInDays: 7 # Optional: Set a log retention period

  # ECS Task Definition
  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: 'expense-portal-task'
      Cpu: '256' # 0.25 vCPU
      Memory: '512' # 0.5 GB
      NetworkMode: 'awsvpc'
      RequiresCompatibilities:
        - 'FARGATE'
      ExecutionRoleArn: !Ref TaskExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: 'expense-portal-container'
          Image: !Ref ImageURI
          PortMappings:
            - ContainerPort: 8080
          EntryPoint:
            - sh
            - -c
          Command:
            - |
              echo "--- Debugging Environment Variables ---"
              echo "SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL"
              echo "SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME"
              echo "SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD"
              echo "--- Starting Application ---"
              java -jar app.jar
          Environment:
            - Name: SPRING_DATASOURCE_URL
              Value:
                Fn::Sub:
                  - 'jdbc:postgresql://${DbEndpoint}:5432/expense_db'
                  - DbEndpoint: !ImportValue
                      'Fn::Sub': '${DatabaseStackName}-DbEndpointAddress'
            - Name: 'SPRING_DATASOURCE_USERNAME'
              Value: 'expense_user'
            - Name: 'SPRING_DATASOURCE_PASSWORD'
              Value: 'expense_pass' # Hardcoded password
            - Name: 'JWT_SECRET'
              Value: !Ref JwtSecret
            - Name: 'AWS_S3_BUCKET_NAME'
              Value: !Ref ReceiptsBucket
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Ref TaskLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'ecs'

  # ECS Service
  EcsService:
    Type: 'AWS::ECS::Service'
    DependsOn: Listener
    Properties:
      ServiceName: 'expense-portal-service'
      Cluster: !Ref EcsCluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: 'FARGATE'
      HealthCheckGracePeriodSeconds: 120 # Add a 2-minute grace period
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Split
            - ","
            - !ImportValue
                Fn::Sub: "${NetworkStackName}-PrivateSubnetIds"
          SecurityGroups:
            - !Ref EcsSecurityGroup
      LoadBalancers:
        - ContainerName: 'expense-portal-container'
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroup

Outputs:
  EcsSecurityGroupId:
    Description: 'The ID of the ECS Service Security Group'
    Value: !Ref EcsSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-EcsSecurityGroupId'
  LoadBalancerDNS:
    Description: 'The DNS name of the Application Load Balancer'
    Value: !GetAtt LoadBalancer.DNSName

Conditions:
  HasS3BucketName: !Not [!Equals [!Ref S3BucketName, ""]]
